---
- name: 'Install Ruby Application'
  hosts: all
  become: true

  pre_tasks:
  - name: 'Install NGINX'
    include_role: 
      name: nginxinc.nginx_core.nginx

  - name: 'Install Postgres'
    include_role:
      name: install_postgres

  roles:
    - deploy_app

        
